### ISSUE TITLE
npm-debug.log

### ISSUE THREAD

**Issue by amccur** [Ismaestro/angular2-tour-of-heroes#1]
I tried to install your version in my terminal, but it keeps saying I need "npm-debug.log" every time. And, I installed the latest versions of nodeJS and npm.

`> angular-hero-cli@0.0.0 start /Users/AndrewMcCurtis/Desktop/angular2-heroes
> npm run server | npm run ng

> angular-hero-cli@0.0.0 ng /Users/AndrewMcCurtis/Desktop/angular2-heroes
> ng serve --proxy-config proxy.conf.json

No errors
Error: No errors
    at validate (/Users/name/Desktop/angular2-heroes/node_modules/extract-text-webpack-plugin/schema/validator.js:10:9)
    at Function.ExtractTextPlugin.extract (/Users/name/Desktop/angular2-heroes/node_modules/extract-text-webpack-plugin/index.js:188:3)
    at /Users/name/Desktop/angular2-heroes/node_modules/angular-cli/models/webpack-build-utils.js:72:77
    at Array.map (native)
    at Object.makeCssLoaders (/Users/name/Desktop/angular2-heroes/node_modules/angular-cli/models/webpack-build-utils.js:69:53)
    at Object.getWebpackCommonConfig (/Users/name/Desktop/angular2-heroes/node_modules/angular-cli/models/webpack-build-common.js:77:65)
    at new NgCliWebpackConfig (/Users/name/Desktop/angular2-heroes/node_modules/angular-cli/models/webpack-config.js:22:49)
    at Class.run (/Users/name/Desktop/angular2-heroes/node_modules/angular-cli/tasks/serve-webpack.js:20:22)
    at /Users/name/Desktop/angular2-heroes/node_modules/angular-cli/commands/serve.js:108:26
    at process._tickCallback (internal/process/next_tick.js:103:7)

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "ng"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular-hero-cli@0.0.0 ng: `ng serve --proxy-config proxy.conf.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-hero-cli@0.0.0 ng script 'ng serve --proxy-config proxy.conf.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-hero-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng serve --proxy-config proxy.conf.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-hero-cli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-hero-cli
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/name/Desktop/angular2-heroes/npm-debug.log`

Thanks

**Comment by Ismaestro** [comment]
Hey,

tell me what SO are you using?

Did you run `npm install` without problem? try as sudo/administrator...

try this commands and tell me what happend?

`
npm run server
`
`
npm run ng
`
